# Do not modify! Generated by:
#   sudo nixos-generate-config --show-hardware-config --root /mnt > ./hosts/nixos/vivo/hardware.nix
{
  flake,
  lib,
  pkgs,
  ...
}:
{
  boot = {
    # Ice Lake modules - adjust after nixos-generate-config
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    kernelModules = [ "kvm-intel" ];
  };

  hardware.enableRedistributableFirmware = lib.mkDefault true;

  # SSD periodic trim
  services.fstrim.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
